# Generated by Django 2.2.5 on 2019-12-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesection',
            name='common_section',
            field=models.BooleanField(default=0, verbose_name='Основной раздел'),
            preserve_default=False,
        ),
    ]
