# Generated by Django 2.2.5 on 2019-12-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191223_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(through='articles.ArticleSection', to='articles.Section'),
        ),
    ]
