# Generated by Django 2.2.5 on 2019-12-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20191223_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(related_name='scopes', through='articles.ArticleSection', to='articles.Section'),
        ),
    ]
