# Generated by Django 2.2.5 on 2019-12-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20191223_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(related_name='scope', through='articles.ArticleSection', to='articles.Section'),
        ),
    ]
