# Generated by Django 2.2.5 on 2019-12-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20191230_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
        migrations.AddField(
            model_name='section',
            name='articles',
            field=models.ManyToManyField(related_name='articles', through='articles.ArticleSection', to='articles.Article'),
        ),
    ]
