# Generated by Django 2.2.5 on 2019-12-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20191230_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='articles',
        ),
        migrations.AddField(
            model_name='section',
            name='chain',
            field=models.ManyToManyField(related_name='chain', through='articles.ArticleSection', to='articles.Article'),
        ),
    ]
