# Generated by Django 2.2.5 on 2019-12-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20191230_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='chain',
        ),
        migrations.AddField(
            model_name='section',
            name='chains',
            field=models.ManyToManyField(through='articles.ArticleSection', to='articles.Article'),
        ),
    ]
