# Generated by Django 2.2.5 on 2019-12-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20191230_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='chains',
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(through='articles.ArticleSection', to='articles.Section'),
        ),
    ]
